version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profit_tracker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/profit_tracker
      JWT_SECRET: supersecret
      CLIENT_URL: http://localhost:4000
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "4000:4000"
    depends_on:
      - backend

volumes:
  db_data:
